"""empty message

Revision ID: 200e5d47c37c
Revises: c77217ece505
Create Date: 2016-12-10 22:49:04.825508

"""

# revision identifiers, used by Alembic.
revision = '200e5d47c37c'
down_revision = 'c77217ece505'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('role', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'role')
    ### end Alembic commands ###
