"""empty message

Revision ID: 41c073a46b63
Revises: 5aae5ada6624
Create Date: 2016-04-08 00:34:28.952489

"""

# revision identifiers, used by Alembic.
revision = '41c073a46b63'
down_revision = '5aae5ada6624'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
