"""empty message

Revision ID: 5aae5ada6624
Revises: None
Create Date: 2016-02-27 14:15:21.751691

"""

# revision identifiers, used by Alembic.
revision = '5aae5ada6624'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
