"""empty message

Revision ID: a32aa06c0efb
Revises: None
Create Date: 2016-12-10 18:16:16.197155

"""

# revision identifiers, used by Alembic.
revision = 'a32aa06c0efb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('phones', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('zipcode', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('issues_reps',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['rep.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'rep_id')
    )
    op.create_table('zipcode',
    sa.Column('zipcode', sa.String(length=5), nullable=False),
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['rep.id'], ),
    sa.PrimaryKeyConstraint('zipcode', 'rep_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode')
    op.drop_table('issues_reps')
    op.drop_table('user')
    op.drop_table('rep')
    op.drop_table('issue')
    ### end Alembic commands ###
