"""empty message

Revision ID: c77217ece505
Revises: a32aa06c0efb
Create Date: 2016-12-10 20:09:45.933639

"""

# revision identifiers, used by Alembic.
revision = 'c77217ece505'
down_revision = 'a32aa06c0efb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues_reps')
    op.add_column('issue', sa.Column('code', sa.String(length=32), nullable=True))
    op.add_column('issue', sa.Column('level', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'level')
    op.drop_column('issue', 'code')
    op.create_table('issues_reps',
    sa.Column('issue_id', sa.INTEGER(), nullable=False),
    sa.Column('rep_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], [u'issue.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], [u'rep.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'rep_id')
    )
    ### end Alembic commands ###
