"""empty message

Revision ID: ed657e16ce20
Revises: 41c073a46b63
Create Date: 2016-08-28 11:50:20.973452

"""

# revision identifiers, used by Alembic.
revision = 'ed657e16ce20'
down_revision = '41c073a46b63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
